NewsPortal/NewsPortal/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('protect.urls')),
    path('sign/', include('sign.urls')),
    path('news/', include('news.urls')),
    path('accounts/', include('allauth.urls')),

]

NewsPortal/news/urls.py
from .views import *
from django.urls import path
from django.views.decorators.cache import cache_page
from .views import (PostDetail, PostSearch,)
from django.contrib.auth.views import LoginView, LogoutView
# from .views import IndexView

urlpatterns = [
    # path('', IndexView.as_view()),
    path('', cache_page(60)(Posts.as_view())),
    path('authors/', AuthorsPage.as_view()),
    path('post/<int:pk>/', cache_page(300)(PostDetail.as_view())),
    path('post2/', PostsList.as_view()),
    path('search/', PostSearch.as_view(), name='post_search'),
    path('create/', PostCreate.as_view(), name='news_create'),
    path('<int:pk>/edit', PostUpdate.as_view(), name='news_edit'),
    path('<int:pk>/delete', PostDelete.as_view(), name='news_delete'),
    path('articles/create/', PostCreate.as_view(), name='articles_create'),
    path('articles/<int:pk>/edit/', PostUpdate.as_view(), name='articles_edit'),
    path('articles/<int:pk>/delete/', PostDelete.as_view(), name='articles_delete'),
    path('login/', LoginView.as_view(template_name='sign/login.html'), name='login'),
    path('logout/', LogoutView.as_view(template_name='sign/logout.html'), name='logout'),
    path('categories/<int:pk>', CategoryListView.as_view(), name='category_list'),
    path('categories/<int:pk>/subscribe', subscribe, name='subscribe'),
    path('categories/<int:pk>/unsubscribe', unsubscribe, name='unsubscribe'),
]

NewsPortal/news/models.py
from datetime import datetime
from django.db.models import Sum
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from django import forms
from django.core.cache import cache

world = 'WD'
politic = 'PL'
business = 'BS'
health = 'HL'
culture = 'CL'
society = 'SC'
accidents = 'AC'
sport = 'SP'
it = 'IT'
science = 'SN'
economy = 'EC'

OPTIONS_CATEGORY = [
    (world, 'Мир'),
    (politic, 'Политика'),
    (business, 'Бизнес'),
    (health, 'Здоровье'),
    (culture, 'Культура'),
    (society, 'Общество'),
    (accidents, 'Проишествия'),
    (sport, 'Спорт'),
    (it, 'ИТ'),
    (science, 'Наука'),
    (economy, 'Экономика')]

article = 'AR'
news = 'NW'

OPTIONS_POST = [
    (article, 'Статья'),
    (news, 'Новость')
]


class Author(models.Model):
    """
    Модель Author
    имеет следующие поля:
    -<portalUser> связь «один к одному» с встроенной моделью пользователей User;
    - <ratingAuthor> рейтинг пользователя.
    """
    authorUser = models.OneToOneField(User, on_delete=models.CASCADE)
    ratingAuthor = models.SmallIntegerField(default=0)

    def update_rating(self):
        """
        - update_rating() модели Author, который обновляет рейтинг пользователя, переданный в аргумент этого метода.
        Он состоит из следующего:
        -суммарный рейтинг каждой статьи автора умножается на 3;
        -суммарный рейтинг всех комментариев автора;
        -суммарный рейтинг всех комментариев к статьям автора.
        """

        postR = self.post_set.all().aggregate(postRating=Sum('rating'))
        p_R = 0
        p_R += postR.get('postRating')

        commentR = self.authorUser.comment_set.all().aggregate(commentRating=Sum('rating'))
        c_R = 0
        c_R += commentR.get('commentRating')

        self.ratingAuthor = p_R * 3 + c_R
        self.save()

    def __str__(self):
        return f"{self.authorUser}"


class Category(models.Model):
    name = models.CharField(max_length=64, unique=True)
    subscribers = models.ManyToManyField(User, related_name='categories', blank=True, null=True)

    def __str__(self):
        return self.name


class Post(models.Model):
    author = models.ForeignKey(Author, on_delete=models.CASCADE, null=True, default=0)
    categoryType = models.CharField(max_length=2, choices=OPTIONS_POST, default=article)
    dataCreations = models.DateTimeField(auto_now_add=True)
    postCategory = models.ManyToManyField(Category, through='PostCategory')
    title = models.CharField(max_length=128)
    text = models.TextField()
    rating = models.SmallIntegerField(default=0)

    def get_absolute_url(self):
        return f'/news/{self, id}'

    def like(self):
        self.rating += 1
        self.save()

    def dislike(self):
        self.rating -= 1
        self.save()

    def preview(self):
        """
        - preview() модели Post, который возвращает начало статьи
        (предварительный просмотр) длиной 124 символа и добавляет многоточие в конце.
        """
        return self.text[0:128] + '...'

    def __str__(self):
        dataf = 'Post from {}'.format(self.dataCreations.strftime('%d.%m.%Y %H:%M'))
        return f"{dataf},{self.author},{self.title}"

    def get_absolute_url(self):  # добавим абсолютный путь, чтобы после создания нас перебрасывало на страницу с товаром
        return f'/post/{self.id}'

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)  # сначала вызываем метод родителя, чтобы объект сохранился
        cache.delete(f'post-{self.pk}')  # затем удаляем его из кэша, чтобы сбросить его

class PostCategory(models.Model):
    """
    Модель PostCategory
    Промежуточная модель для связи «многие ко многим»:
    - <postThrough>     связь «один ко многим» с моделью Post;
    - <categoryThrough> связь «один ко многим» с моделью Category.
    """
    post = models.ForeignKey('Post', on_delete=models.CASCADE)
    category = models.ForeignKey('Category', on_delete=models.CASCADE)

    def __str__(self):
        return self.category.title()


class Comment(models.Model):
    """
    Модель Comment
    Под каждой новостью/статьёй можно оставлять комментарии, поэтому необходимо организовать их способ хранения тоже.
    Модель будет иметь следующие поля:
    - <commentPost>  связь «один ко многим» с моделью Post;
    - <userPost>     связь «один ко многим» со встроенной моделью User
                    (комментарии может оставить любой пользователь, необязательно автор);
    - <text>         текст комментария;
    - <dataCreation> дата и время создания комментария;
    - <rating>       рейтинг комментария.
    """
    commentPost = models.ForeignKey(Post, on_delete=models.CASCADE)
    userPost = models.ForeignKey(User, on_delete=models.CASCADE)
    text = models.TextField()
    dataCreation = models.DateTimeField(auto_now_add=True)
    rating = models.SmallIntegerField(default=0)

    def like(self):
        """
        - like()    который увеличивает рейтинг на единицу.
        """
        self.rating += 1
        self.save()

    def dislike(self):
        """
        - dislike() который уменьшают рейтинг на единицу.
        """
        self.rating -= 1
        self.save()

    def __str__(self):
        return f"{self.dataCreation}, {self.userPost}"


class Post2(models.Model):
    author = models.ForeignKey(Author, on_delete=models.CASCADE)
    view = models.CharField(max_length=2, choices=OPTIONS_POST, default=news)
    time_in = models.DateTimeField(auto_now_add=True)
    title = models.CharField(max_length=150)
    text = models.TextField()
    rating_post = models.IntegerField(default=0)

    def like(self):
        self.rating_post += 1
        self.save()

    def dislike(self):
        self.rating_post -= 1
        self.save()

    def preview(self):
        return self.text[:124] + '...'

    def __str__(self):
        return f'{self.text}'

    def get_absolute_url(self):
        return reverse('post_detail', args=[str(self.id)])


class BaseRegisterForm(UserCreationForm):
    email = forms.EmailField(label="Email")
    first_name = forms.CharField(label="Имя")
    last_name = forms.CharField(label="Фамилия")

    class Meta:
        model = User
        fields = ("username",
                  "first_name",
                  "last_name",
                  "email",
                  "password1",
                  "password2",)


class Appointment(models.Model):
    date = models.DateField(
        default=datetime.utcnow,
    )
    client_name = models.CharField(
        max_length=200
    )
    message = models.TextField()

    def __str__(self):
        return f'{self.client_name}: {self.message}'

NewsPortal/news/forms.py
from django import forms
from django.core.exceptions import ValidationError
from .models import Post
from allauth.account.forms import SignupForm
from django.contrib.auth.models import Group


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = [
            'title',
            'text',
            'author',
            "postCategory"
        ]

    def clean(self):
        cleaned_data = super().clean()
        title = cleaned_data.get('title')
        if title is not None and len(title) > 150:
            raise ValidationError({
                "title": "Заголовок не может содержать более 150 символов"
            })

        text = cleaned_data.get("text")
        if text == title:
            raise ValidationError(
                "Текст не должен быть идентичен заголовку."
            )
        return cleaned_data


class DateInput(forms.DateInput):
    input_type = 'date'


class BasicSignupForm(SignupForm):

    def save(self, request):
        user = super(BasicSignupForm, self).save(request)
        basic_group = Group.objects.get(name='common')
        basic_group.user_set.add(user)
        return user

NewsPortal/news/views.py
from django.http import HttpResponse
from .tasks import *
from django.core.mail import send_mail
from datetime import datetime
from .models import Appointment
from django.views.generic.base import View
from .models import *
from django.urls import reverse_lazy
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView, TemplateView
from .forms import PostForm
from .filters import PostFilter
from django.contrib.auth.models import User, Group
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.shortcuts import redirect, get_object_or_404, render, reverse
from django.contrib.auth.decorators import login_required
from django.core.cache import cache

class PostDetail(LoginRequiredMixin, View):
    def get(self, request, pk):
        ps = Post.objects.get(id=pk)
        return render(request, "news/posts.html", {'ps': ps})

    def get_object(self, *args, **kwargs):  # переопределяем метод получения объекта, как ни странно
        obj = cache.get(f'product-{self.kwargs["pk"]}',
                        None)  # кэш очень похож на словарь, и метод get действует так же. Он забирает значение по ключу, если его нет, то забирает None.

        # если объекта нет в кэше, то получаем его и записываем в кэш
        if not obj:
            obj = super().get_object(queryset=self.queryset)
            cache.set(f'product-{self.kwargs["pk"]}', obj)

        return obj


class Posts(LoginRequiredMixin, PermissionRequiredMixin, ListView):
    model = Post
    ordering = ['-rating']
    template_name = 'news/news.html'
    context_object_name = 'news'
    paginate_by = 5
    permission_required = ('news.add_post','news.change_post')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['filter'] = PostFilter(self.request.GET, queryset=self.get_queryset())
        context['is_not_author'] = not self.request.user.groups.filter(name='authors').exists()
        return context


class AuthorsPage(LoginRequiredMixin, ListView):
    model = Author  # queryset = Author.objects.all()
    context_object_name = "Authors"
    template_name = 'news/authors.html'


class PostsList(LoginRequiredMixin, PermissionRequiredMixin, ListView):
    model = Post2
    ordering = '-time_in'
    template_name = 'news/posts2.html'
    context_object_name = 'posts'
    paginate_by = 5
    permission_required = ('news.add_post','news.change_post')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return context


class PostSearch(LoginRequiredMixin, ListView):
    model = Post
    template_name = 'news/post_search.html'
    context_object_name = 'posts'

    def get_queryset(self):
        queryset = super().get_queryset()
        self.filterset = PostFilter(self.request.GET, queryset)
        return self.filterset.qs

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['filterset'] = self.filterset
        return context


class PostCreate(LoginRequiredMixin, PermissionRequiredMixin, CreateView):
    form_class = PostForm
    model = Post
    template_name = 'news/post_create.html'
    permission_required = ('news.add_post','news.change_post')

    def form_valid(self, form):
        post = form.save(commit=False)
        if self.request.method == 'POST':
            path_info = self.request.META['PATH_INFO']
            if path_info == '/news/create/':
                post.view = 'NW'
            elif path_info == '/articles/create/':
                post.view = 'AR'
        post.save()
        return super().form_valid(form)


class PostUpdate(LoginRequiredMixin, PermissionRequiredMixin, UpdateView):
    form_class = PostForm
    model = Post
    template_name = 'news/post_edit.html'
    permission_required = ('news.add_post', 'news.change_post')
    success_url = 'edit/'

    def get_object(self, **kwargs):
        id = self.kwargs.get('pk')
        return Post.objects.get(pk=id)


class PostDelete(LoginRequiredMixin, DeleteView):
    form_class = PostForm
    model = Post
    template_name = 'news/post_delete.html'
    success_url = reverse_lazy('post_list')


class ProtectedView(LoginRequiredMixin, TemplateView):
    template_name = 'news/news.html'


class CategoryListView(Posts):
    models = Post
    template_name = 'news/category_list.html'
    context_object_name = 'category_news_list'

    def get_queryset(self):
        self.category = get_object_or_404(Category, id=self.kwargs['pk'])
        queryset = Post.objects.filter(postCategory=self.category).order_by('-rating')
        return queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['is_not_subscribers'] = self.request.user not in self.category.subscribers.all()
        context['category'] = self.category
        return context


@login_required
def subscribe(request, pk):
    user = request.user
    category = Category.objects.get(id=pk)
    category.subscribers.add(user)
    message = 'Вы подписались на категорию: '
    return render(request, 'news/subscribe.html', {'category': category, 'message': message})


@login_required
def unsubscribe(request, pk):
    user = request.user
    category = Category.objects.get(id=pk)
    category.subscribers.remove(user)
    message = 'вы отписались от категории: '
    return render(request, 'subscribe.html', {'category': category, 'message': message})

@login_required
def upgrade_me(request):
    user = request.user
    authors_group = Group.objects.get(name='authors')
    if not request.user.groups.filter(name='authors').exists():
        authors_group.user_set.add(user)
    return redirect('/news')



class AppointmentView(View):
    def get(self, request, *args, **kwargs):
        return render(request, 'make_appointment.html', {})

    def post(self, request, *args, **kwargs):
        appointment = Appointment(
            date=datetime.strptime(request.POST['date'], '%Y-%m-%d'),
            client_name=request.POST['client_name'],
            message=request.POST['message'],
        )
        appointment.save()

        # отправляем письмо
        send_mail(
            subject=f'{appointment.client_name} {appointment.date.strftime("%Y-%M-%d")}',
            # имя клиента и дата записи будут в теме для удобства
            message=appointment.message,  # сообщение с кратким описанием проблемы
            from_email='alexander.katleev@yandex.ru',  # здесь указываете почту, с которой будете отправлять
            recipient_list=[]  # здесь список получателей. Например, секретарь, сам врач и т. д.
        )

        return redirect('appointments:make_appointment')


# class IndexView(View):
#     def get(self, request):
#         hello.delay()
#         return HttpResponse('Hello!')

NewsPortal/templates/news/category_list.html
{% extends 'news/default.html' %}
{% load static %}

{% block MyCss %}
<title> {{ news.title }}</title>
<link rel="stylesheet" href="{% static 'css/base.css' %}">
<link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
<link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}">
<script
  src="https://code.jquery.com/jquery-3.6.2.min.js"
  integrity="sha256-2krYZKh//PcchRtd+H+VyyQoZ/e3EcrkxhM8ycwASPA="
  crossorigin="anonymous"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
{% endblock %}

{% block MyContent %}
<div class="navbar navbar-inverse navbar-fixed-top">
    <div class="container">
      <div class="navbar-header">
         <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#collapseMenu">
          <span class="icon-bar">Меню</span>
        </button>
        <a class="navbar-brand" href="#">SkillFactory<i class="fa fa-circle"></i>Python</a>
      </div>
      <div class="collapse" id="collapseMenu" >
        <ul class="nav navbar-nav navbar-right">
          <li><a href="https://apps.skillfactory.ru/" target="_blank">Учебная Платформа</a></li>
          <li><a href=authors/>Авторы</a></li>
          <li><a href=post2/>Другие новости</a></li>
          <li><a href=search/>Поиск новостей</a></li>
          <li><a href=create/>Создать</a></li>
          <li><a href=edit/>Редактировать</a></li>
          <li><a href=categories/<int:pk/>Подписки</a></li>
          <li><a href=../sign/login/>Вход пользователя/Регистрация</a></li>
        </ul>
      </div>
    </div>
</div>
  <div id="headerwrap">
    <div class="container">
      <div class="row centered">
        <div class="col-lg-12 col-lg-offset-2">
          <h1>Страница списка новостей</h1>
          <h2>Наши рейтинги: </h2>
        </div>
      </div>
    </div>
  </div>
  <div class="container w">
    <div class="row centered">
      <div class="col-lg-4">
        <i class="fa fa-heart"></i>
        <h4>Лучший автор новостей и его рейтинг</h4>
      </div>
      <div class="col-lg-4">
        <i class="fa fa-keyboard-o" aria-hidden="true"></i>
        <h4>Лучший комментатор новостей и его рейтинг</h4>
        <p> Имя лучшего комментатора  </p>
      </div>
      <div class="col-lg-4">
        <i class="fa fa-reply" aria-hidden="true"></i>
        <h4>Последний комментарий на сайте</h4>
        <p> Информация о последнем комментарии   </p>
        </p>
      </div>
    </div>
  </div>

  <div class="container wb">
    <div class="row centered">
      <br><br>
      <div class="col-lg-8 col-lg-offset-2">
        <h4>Список новостей по заданию </h4>
        <table >
          <tr>
            <td>ID поста</td>
            <td>Дата создания</td>
            <td>Статья/Новость</td>
            <td>Автор</td>
            <td>Рейтинг поста</td>
            <td>Заголовок</td>
            <td>Категории</td>
          </tr>
              {% for post_n in category_news_list %}
          <tr>
            <td>{{ post_n.pk }}</td>
            <td>{{ post_n.dataCreations }}</td>
            <td> <a{{ post_n.pk }}>{{ post_n.get_categoryType_display }}</a></td>
            <td>{{ post_n.author }}</td>
            <td>{{ post_n.rating }}</td>
            <td class="leftAligned"><a href=post/{{ post_n.pk }}>{{ post_n.title }}</a></td>
            <td class="leftAligned"><a>{% for category in post_n.postCategory.all %}<span>{{ category }}</span><br>
            {% endfor %}
              {% endfor %}
              {% for post in post.postCategory.all%}
                  <a href="{% url 'category_list' category.id%}">{{post.postCategory}}</a>
              {% endfor %}
              </tr>
        </table>
      </div>
  </div>
   {% if page_obj.has_previous %}
       <a href="?page=1">1</a>
       {% if page_obj.previous_page_number != 1 %}
           ...
           <a href="?page={{ page_obj.previous_page_number }}">{{ page_obj.previous_page_number }}</a>
       {% endif %}
   {% endif %}

   {# Информация о текущей странице #}
   {{ page_obj.number }}

   {# Информация о следующих страницах #}
   {% if page_obj.has_next %}
       <a href="?page={{ page_obj.next_page_number }}">{{ page_obj.next_page_number }}</a>
       {% if paginator.num_pages != page_obj.next_page_number %}
           ...
           <a href="?page={{ page_obj.paginator.num_pages }}">{{ page_obj.paginator.num_pages }}</a>
       {% endif %}
   {% endif %}
<hr />
  <div id="lg">
    <div class="container">
      <div class="row centered">
        <div class="col-lg-2 col-lg-offset-1">
          <img src=" {% static 'img/c01.png' %}" alt="">
        </div>
        <div class="col-lg-2">
          <img src=" {% static 'img/c02.png' %}" alt="">
        </div>
        <div class="col-lg-2">
          <img src=" {% static 'img/c03.png' %}" alt="">
        </div>
        <div class="col-lg-2">
          <img src=" {% static 'img/c04.jpg' %}" alt="">
        </div>
      </div>
    </div>
  </div>
    <br><br>
  <div id="r">
    <div class="container">
      <div class="row centered">
        <div class="col-lg-8 col-lg-offset-2">
          <h4>Курс SkillFactory - разработчик на Python</h4>
          <p>SkillFactory — oнлайн-школа IT-профессий.  © 2023</p>
        </div>
      </div>
    </div>
  </div>
  <div id="f">
    <div class="container">
      <div class="row centered">
        <a href="#"><i class="fa fa-twitter"></i></a>
        <a href="#"><i class="fa fa-facebook"></i></a>
        <a href="#"><i class="fa fa-vk"></i></a>
      </div>
    </div>
  </div>
</div>

{% endblock %}

NewsPortal/templates/news/news.html
{% extends 'news/default.html' %}
{% load static %}
{% load custom_filters %}
{% load custom_tags %}
{% load cache %}

{% block title %}
Post
{% endblock title %}
{% cache 30 MyCss %}
{% block MyCss %}
<title> {{ news.title }}</title>
<link rel="stylesheet" href="{% static 'css/base.css' %}">
<link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
<link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}">
<script
  src="https://code.jquery.com/jquery-3.6.2.min.js"
  integrity="sha256-2krYZKh//PcchRtd+H+VyyQoZ/e3EcrkxhM8ycwASPA="
  crossorigin="anonymous"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
{% endblock %}
{% endcache %}


{% block MyContent %}
<div class="navbar navbar-inverse navbar-fixed-top">
    <div class="container">
      <div class="navbar-header">
         <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#collapseMenu">
          <span class="icon-bar">Меню</span>
        </button>
        <a class="navbar-brand" href="#">SkillFactory<i class="fa fa-circle"></i>Python</a>
      </div>
      <div class="collapse" id="collapseMenu" >
        <ul class="nav navbar-nav navbar-right">
          <li><a href="https://apps.skillfactory.ru/" target="_blank">Учебная Платформа</a></li>
          <li><a href=authors/>Авторы</a></li>
          <li><a href=post2/>Другие новости</a></li>
          <li><a href=search/>Поиск новостей</a></li>
          <li><a href=create/>Создать</a></li>
          <li><a href=articles/<int:pk>/edit//>Редактировать</a></li>
          <li><a href=categories/<int:pk/>Подписки</a></li>
          <li><a href=../sign/login/>Вход пользователя/Регистрация</a></li>
        </ul>
      </div>
    </div>
</div>
  <div id="headerwrap">
    <div class="container">
      <div class="row centered">
        <div class="col-lg-12 col-lg-offset-2">
          <h1>Страница списка новостей</h1>
          <h2>Наши рейтинги: </h2>
        </div>
      </div>
    </div>
  </div>
  <div class="container w">
    <div class="row centered">
      <div class="col-lg-4">
        <i class="fa fa-heart"></i>
        <h4>Лучший автор новостей и его рейтинг</h4>
      </div>
      <div class="col-lg-4">
        <i class="fa fa-keyboard-o" aria-hidden="true"></i>
        <h4>Лучший комментатор новостей и его рейтинг</h4>
        <p> Имя лучшего комментатора  </p>
      </div>
      <div class="col-lg-4">
        <i class="fa fa-reply" aria-hidden="true"></i>
        <h4>Последний комментарий на сайте</h4>
        <p> Информация о последнем комментарии   </p>
        </p>
      </div>
    </div>
  </div>

  <div class="container wb">
    <div class="row centered">
      <br><br>
      <div class="col-lg-8 col-lg-offset-2">
        <h4>Список новостей по заданию </h4>
          {% if is_not_subscriber %}
              <p class="text-center"><a href="{%url 'subscribe' category.id%}"class="btn btn-secondary btn-sm">Подписаться на категорию</a></p>
          {% endif%}
        <table >
          <tr>
            <td>ID поста</td>
            <td>Дата создания</td>
            <td>Статья/Новость</td>
            <td>Автор</td>
            <td>Рейтинг поста</td>
            <td>Заголовок</td>
            <td>Категории</td>
          </tr>
              {% for post_n in news %}
          <tr>
            <td>{{ post_n.pk }}</td>
            <td>{{ post_n.dataCreations }}</td>
            <td> <a{{ post_n.pk }}>{{ post_n.get_categoryType_display }}</a></td>
            <td>{{ post_n.author }}</td>
            <td>{{ post_n.rating }}</td>
            <td class="leftAligned"><a href=post/{{ post_n.pk }}>{{ post_n.title }}</a></td>
            <td class="leftAligned"><a href='categories/{{ post_n.pk }}'>{% for category in post_n.postCategory.all %}<span>{{ category }}</span><br>
            {% endfor %}
            {% endfor %}
            {% for post in category_news_list %}
            <td>{% for category in post.postCategory.all %}
            <td class="leftAligned"><a href="categories/{{ category.id }}">{{ postCategory }}</a></td>
            {% endfor %}
{% endfor %}
        </table>
      </div>
  </div>
   {% if page_obj.has_previous %}
       <a href="?page=1">1</a>
       {% if page_obj.previous_page_number != 1 %}
           ...
           <a href="?page={{ page_obj.previous_page_number }}">{{ page_obj.previous_page_number }}</a>
       {% endif %}
   {% endif %}

   {# Информация о текущей странице #}
   {{ page_obj.number }}

   {# Информация о следующих страницах #}
   {% if page_obj.has_next %}
       <a href="?page={{ page_obj.next_page_number }}">{{ page_obj.next_page_number }}</a>
       {% if paginator.num_pages != page_obj.next_page_number %}
           ...
           <a href="?page={{ page_obj.paginator.num_pages }}">{{ page_obj.paginator.num_pages }}</a>
       {% endif %}
   {% endif %}
<hr />
  <div id="lg">
    <div class="container">
      <div class="row centered">
        <div class="col-lg-2 col-lg-offset-1">
          <img src=" {% static 'img/c01.png' %}" alt="">
        </div>
        <div class="col-lg-2">
          <img src=" {% static 'img/c02.png' %}" alt="">
        </div>
        <div class="col-lg-2">
          <img src=" {% static 'img/c03.png' %}" alt="">
        </div>
        <div class="col-lg-2">
          <img src=" {% static 'img/c04.jpg' %}" alt="">
        </div>
      </div>
    </div>
  </div>
    <br><br>
  <div id="r">
    <div class="container">
      <div class="row centered">
        <div class="col-lg-8 col-lg-offset-2">
          <h4>Курс SkillFactory - разработчик на Python</h4>
          <p>SkillFactory — oнлайн-школа IT-профессий.  © 2023</p>
        </div>
      </div>
    </div>
  </div>
  <div id="f">
    <div class="container">
      <div class="row centered">
        <a href="#"><i class="fa fa-twitter"></i></a>
        <a href="#"><i class="fa fa-facebook"></i></a>
        <a href="#"><i class="fa fa-vk"></i></a>
      </div>
    </div>
  </div>
</div>
{% endblock %}